# fly.toml app configuration file generated for veilcore on 2026-09-03T22:54:19+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'veilcore'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '5174'

[http_service]
  internal_port = 5174
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/__veilcore/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
